/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vcell

import kotlin.test.Test
import kotlin.test.assertNotNull

class CellTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Vcell()
    }
}
