/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vx

import kotlin.test.Test
import kotlin.test.assertNotNull

class VxTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Vx()
    }
}
